package org.amit.finwise.policy.model;

public enum PolicyTransmissionChannel {
    DISCOUNT_RATE,
    CREDIT_SUPPLY,
    CREDIT_COST,
    EARNINGS,
    CASHFLOWS_AFTER_TAX,
    LIQUIDITY_MARKET_ACCESS,
    RISK_PREMIUM_REGIME,
    COMPLIANCE_COST,
    MARKET_STRUCTURE,
    SECTOR_MARGIN,
    LIQUIDITY_RULE,
    FISCAL_STIMULUS,
    FII_REGULATORY,
    OTHER
}
