package org.amit.finwise.policy.model;

public enum PolicyActionType {
    RATE_CHANGE,
    LIQUIDITY_OPERATION,
    CAPITAL_REQUIREMENT,
    DISCLOSURE_RULE,
    TAX_RATE_CHANGE,
    TDS_CHANGE,
    ELIGIBILITY_CHANGE,
    LOCKIN_CHANGE,
    POSITION_LIMIT_CHANGE,
    REPORTING_REQUIREMENT,
    COMPLIANCE_CHANGE,
    MARKET_STRUCTURE_CHANGE,
    GOVERNMENT_SCHEME,
    GUIDANCE_SIGNAL,
    OTHER
}
