-- Flyway baseline: schema as of Phase 2 (Hibernate ddl-auto=update era)
-- Generated from a running expense_tracker database on 2026-06-21

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.budgets (
    id bigint NOT NULL,
    alert_sent boolean,
    alert_threshold numeric(38,2),
    budget_limit numeric(38,2) NOT NULL,
    budget_month character varying(7) NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_over_budget boolean NOT NULL,
    percent_spent numeric(38,2),
    remaining numeric(38,2),
    spent numeric(38,2) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT budgets_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD_DINING'::character varying, 'GROCERIES'::character varying, 'TRANSPORTATION'::character varying, 'UTILITIES'::character varying, 'ENTERTAINMENT'::character varying, 'SHOPPING'::character varying, 'HEALTHCARE'::character varying, 'INSURANCE'::character varying, 'SUBSCRIPTION'::character varying, 'INVESTMENT'::character varying, 'SAVINGS'::character varying, 'EDUCATION'::character varying, 'PERSONAL_CARE'::character varying, 'HOME_MAINTENANCE'::character varying, 'TRAVEL'::character varying, 'BUSINESS'::character varying, 'CHARITY'::character varying, 'DEBT_PAYMENT'::character varying, 'TAXES'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT budgets_status_check CHECK (((status)::text = ANY ((ARRAY['ON_TRACK'::character varying, 'WARNING'::character varying, 'OVER_BUDGET'::character varying])::text[])))
);
ALTER TABLE public.budgets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budgets_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.budgets ADD CONSTRAINT budgets_pkey PRIMARY KEY (id);

CREATE TABLE public.cfo_ai_insights (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    emailed boolean,
    insight_date date NOT NULL,
    insight_type character varying(255) NOT NULL,
    model_used character varying(255),
    read boolean,
    title character varying(255) NOT NULL,
    tokens_used integer,
    user_id character varying(255) NOT NULL,
    CONSTRAINT cfo_ai_insights_insight_type_check CHECK (((insight_type)::text = ANY ((ARRAY['DAILY_BRIEF'::character varying, 'PORTFOLIO_ALERT'::character varying, 'GOAL_ADVICE'::character varying, 'NEWS_SUMMARY'::character varying, 'REBALANCE_ALERT'::character varying, 'MARKET_INSIGHT'::character varying, 'EXPENSE_ALERT'::character varying, 'CHAT_RESPONSE'::character varying])::text[])))
);
ALTER TABLE public.cfo_ai_insights ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_ai_insights_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_ai_insights ADD CONSTRAINT cfo_ai_insights_pkey PRIMARY KEY (id);

CREATE TABLE public.cfo_auth_tokens (
    id bigint NOT NULL,
    auto_refresh_enabled boolean,
    created_at timestamp(6) without time zone NOT NULL,
    encrypted_credentials text,
    encrypted_token text NOT NULL,
    expires_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    last_used_at timestamp(6) without time zone,
    service character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL
);
ALTER TABLE public.cfo_auth_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_auth_tokens_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_auth_tokens ADD CONSTRAINT cfo_auth_tokens_pkey PRIMARY KEY (id);

CREATE TABLE public.cfo_investor_behavior (
    id bigint NOT NULL,
    active_symbol_count integer,
    avg_holding_duration_days double precision,
    closed_positions_analyzed integer,
    computed_at timestamp(6) without time zone NOT NULL,
    concentrationhhi double precision,
    created_at timestamp(6) without time zone NOT NULL,
    derived_risk_appetite character varying(255),
    hypocrisy_score integer,
    panic_sell_count integer,
    panic_sell_ratio double precision,
    patience_index double precision,
    sector_affinity_json text,
    trades_per_month double precision,
    trading_style character varying(255),
    transaction_count integer,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    win_rate double precision,
    CONSTRAINT cfo_investor_behavior_derived_risk_appetite_check CHECK (((derived_risk_appetite)::text = ANY ((ARRAY['CONSERVATIVE'::character varying, 'MODERATE'::character varying, 'AGGRESSIVE'::character varying])::text[]))),
    CONSTRAINT cfo_investor_behavior_trading_style_check CHECK (((trading_style)::text = ANY ((ARRAY['SCALPER'::character varying, 'ACTIVE_TRADER'::character varying, 'LONG_TERM_HOLDER'::character varying])::text[])))
);
CREATE SEQUENCE public.cfo_investor_behavior_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.cfo_investor_behavior_id_seq OWNED BY public.cfo_investor_behavior.id;
ALTER TABLE ONLY public.cfo_investor_behavior ALTER COLUMN id SET DEFAULT nextval('public.cfo_investor_behavior_id_seq'::regclass);
ALTER TABLE ONLY public.cfo_investor_behavior ADD CONSTRAINT cfo_investor_behavior_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cfo_investor_behavior ADD CONSTRAINT uk_ixnqibik8dxqfjrn0474d6267 UNIQUE (user_id);

CREATE TABLE public.cfo_news_articles (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    published_at timestamp(6) without time zone,
    published_date date,
    related_sectors character varying(500),
    related_symbols character varying(500),
    relevance_level character varying(255),
    relevance_score integer,
    sentiment character varying(255),
    source character varying(255) NOT NULL,
    summary text,
    title text NOT NULL,
    url text,
    llm_impact_note character varying(500),
    llm_reviewed boolean DEFAULT false,
    tier1_confidence double precision DEFAULT 0.5,
    actionability_score integer,
    impact_horizon character varying(255),
    impact_type character varying(255),
    sector_impact text,
    entity_sentiments text,
    fundamental_sentiment character varying(255),
    CONSTRAINT cfo_news_articles_category_check CHECK (((category)::text = ANY ((ARRAY['EARNINGS'::character varying, 'IPO'::character varying, 'CORPORATE_ACTION'::character varying, 'ANALYST_RECOMMENDATION'::character varying, 'POLICY'::character varying, 'REGULATORY'::character varying, 'MARKET'::character varying, 'SECTOR'::character varying, 'MACRO'::character varying, 'MACRO_RISK'::character varying, 'GEOPOLITICAL'::character varying, 'GLOBAL'::character varying, 'ECONOMY'::character varying, 'CORPORATE'::character varying])::text[]))),
    CONSTRAINT cfo_news_articles_fundamental_sentiment_check CHECK (((fundamental_sentiment)::text = ANY ((ARRAY['POSITIVE'::character varying, 'NEGATIVE'::character varying, 'NEUTRAL'::character varying])::text[]))),
    CONSTRAINT cfo_news_articles_impact_horizon_check CHECK (((impact_horizon)::text = ANY ((ARRAY['SHORT_TERM'::character varying, 'MEDIUM_TERM'::character varying, 'LONG_TERM'::character varying])::text[]))),
    CONSTRAINT cfo_news_articles_impact_type_check CHECK (((impact_type)::text = ANY ((ARRAY['MACRO'::character varying, 'SECTOR'::character varying, 'STOCK'::character varying, 'POLICY'::character varying, 'REGULATORY'::character varying, 'MIXED'::character varying])::text[]))),
    CONSTRAINT cfo_news_articles_relevance_level_check CHECK (((relevance_level)::text = ANY ((ARRAY['HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying])::text[]))),
    CONSTRAINT cfo_news_articles_sentiment_check CHECK (((sentiment)::text = ANY ((ARRAY['POSITIVE'::character varying, 'NEGATIVE'::character varying, 'NEUTRAL'::character varying])::text[])))
);
ALTER TABLE public.cfo_news_articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_news_articles_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_news_articles ADD CONSTRAINT cfo_news_articles_pkey PRIMARY KEY (id);

CREATE TABLE public.cfo_news_embeddings (
    article_id bigint NOT NULL,
    embedding public.vector(768),
    created_at timestamp without time zone DEFAULT now()
);
ALTER TABLE ONLY public.cfo_news_embeddings ADD CONSTRAINT cfo_news_embeddings_pkey PRIMARY KEY (article_id);

CREATE TABLE public.cfo_pdf_uploads (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    error_message text,
    institution character varying(255),
    original_filename character varying(255) NOT NULL,
    parse_status character varying(255) NOT NULL,
    pdf_type character varying(255),
    statement_period_end character varying(255),
    statement_period_start character varying(255),
    storage_path character varying(255) NOT NULL,
    transactions_extracted integer,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT cfo_pdf_uploads_parse_status_check CHECK (((parse_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'PASSWORD_REQUIRED'::character varying])::text[]))),
    CONSTRAINT cfo_pdf_uploads_pdf_type_check CHECK (((pdf_type)::text = ANY ((ARRAY['BANK_STATEMENT'::character varying, 'CREDIT_CARD_STATEMENT'::character varying, 'MF_STATEMENT'::character varying, 'DEMAT_STATEMENT'::character varying, 'TRANSACTION_RECEIPT'::character varying, 'UNKNOWN'::character varying])::text[])))
);
ALTER TABLE public.cfo_pdf_uploads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_pdf_uploads_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_pdf_uploads ADD CONSTRAINT cfo_pdf_uploads_pkey PRIMARY KEY (id);

CREATE TABLE public.cfo_portfolio_snapshots (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_value numeric(38,2),
    day_pnl numeric(38,2),
    day_pnl_percent numeric(38,2),
    holdings_count integer,
    overall_pnl_percent numeric(38,2),
    raw_snapshot_json text,
    snapshot_time timestamp(6) without time zone NOT NULL,
    source character varying(255) NOT NULL,
    total_invested numeric(38,2),
    unrealized_pnl numeric(38,2),
    user_id character varying(255) NOT NULL
);
ALTER TABLE public.cfo_portfolio_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_portfolio_snapshots_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_portfolio_snapshots ADD CONSTRAINT cfo_portfolio_snapshots_pkey PRIMARY KEY (id);

CREATE TABLE public.cfo_risk_questionnaire (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    drawdown_reaction character varying(255),
    emergency_fund_months integer,
    income_stability_rating integer,
    investment_horizon_years integer,
    max_acceptable_loss_percent integer,
    primary_goal_focus character varying(255),
    stated_risk_score integer,
    updated_at timestamp(6) without time zone,
    user_id character varying(255) NOT NULL,
    CONSTRAINT cfo_risk_questionnaire_drawdown_reaction_check CHECK (((drawdown_reaction)::text = ANY ((ARRAY['SELL_IMMEDIATELY'::character varying, 'HOLD_AND_WAIT'::character varying, 'BUY_MORE'::character varying])::text[]))),
    CONSTRAINT cfo_risk_questionnaire_primary_goal_focus_check CHECK (((primary_goal_focus)::text = ANY ((ARRAY['CAPITAL_PRESERVATION'::character varying, 'REGULAR_INCOME'::character varying, 'BALANCED'::character varying, 'CAPITAL_GROWTH'::character varying])::text[])))
);
CREATE SEQUENCE public.cfo_risk_questionnaire_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.cfo_risk_questionnaire_id_seq OWNED BY public.cfo_risk_questionnaire.id;
ALTER TABLE ONLY public.cfo_risk_questionnaire ALTER COLUMN id SET DEFAULT nextval('public.cfo_risk_questionnaire_id_seq'::regclass);
ALTER TABLE ONLY public.cfo_risk_questionnaire ADD CONSTRAINT cfo_risk_questionnaire_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cfo_risk_questionnaire ADD CONSTRAINT uk_t4sr9uem4idcbb374ivhm27m UNIQUE (user_id);

CREATE TABLE public.cfo_stock_price_history (
    id bigint NOT NULL,
    close_price numeric(12,2),
    consecutive_circuit_count integer,
    created_at timestamp(6) without time zone NOT NULL,
    high_price numeric(12,2),
    hit_lower_circuit boolean,
    hit_upper_circuit boolean,
    low_price numeric(12,2),
    open_price numeric(12,2),
    price_change_percent double precision,
    price_date date NOT NULL,
    symbol character varying(30) NOT NULL,
    volume bigint
);
CREATE SEQUENCE public.cfo_stock_price_history_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.cfo_stock_price_history_id_seq OWNED BY public.cfo_stock_price_history.id;
ALTER TABLE ONLY public.cfo_stock_price_history ALTER COLUMN id SET DEFAULT nextval('public.cfo_stock_price_history_id_seq'::regclass);
ALTER TABLE ONLY public.cfo_stock_price_history ADD CONSTRAINT cfo_stock_price_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cfo_stock_price_history ADD CONSTRAINT uq_price_symbol_date UNIQUE (symbol, price_date);

CREATE TABLE public.cfo_transactions (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dedup_hash character varying(255) NOT NULL,
    description text,
    name character varying(255),
    pdf_upload_id bigint,
    price_per_unit numeric(38,2),
    quantity numeric(38,2),
    reference_number character varying(255),
    source character varying(255) NOT NULL,
    symbol character varying(255),
    synced_to_expense boolean,
    transaction_date date NOT NULL,
    transaction_type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT cfo_transactions_source_check CHECK (((source)::text = ANY ((ARRAY['GROWW'::character varying, 'BANK_PDF'::character varying, 'CREDIT_CARD_PDF'::character varying, 'MF_PDF'::character varying, 'DEMAT_PDF'::character varying, 'MANUAL'::character varying])::text[]))),
    CONSTRAINT cfo_transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['BUY'::character varying, 'SELL'::character varying, 'DIVIDEND'::character varying, 'INTEREST'::character varying, 'EXPENSE'::character varying, 'INCOME'::character varying, 'TRANSFER'::character varying, 'FEE'::character varying, 'TAX'::character varying, 'OTHER'::character varying])::text[])))
);
ALTER TABLE public.cfo_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_transactions_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_transactions ADD CONSTRAINT cfo_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cfo_transactions ADD CONSTRAINT idx_txn_hash UNIQUE (dedup_hash);

CREATE TABLE public.cfo_user_profiles (
    id bigint NOT NULL,
    additional_context text,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    investment_horizon_years integer,
    monthly_fixed_expenses numeric(38,2),
    monthly_income numeric(38,2),
    name character varying(255),
    primary_goal_description text,
    risk_appetite character varying(255),
    target_monthly_savings numeric(38,2),
    target_portfolio_value numeric(38,2),
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT cfo_user_profiles_risk_appetite_check CHECK (((risk_appetite)::text = ANY ((ARRAY['CONSERVATIVE'::character varying, 'MODERATE'::character varying, 'AGGRESSIVE'::character varying])::text[])))
);
ALTER TABLE public.cfo_user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfo_user_profiles_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.cfo_user_profiles ADD CONSTRAINT cfo_user_profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cfo_user_profiles ADD CONSTRAINT uk1y38x7syast7a6e70yetxer0t UNIQUE (user_id);

CREATE TABLE public.document_uploads (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_type character varying(255),
    error_message text,
    expenses_extracted integer,
    institution character varying(255),
    original_filename character varying(255) NOT NULL,
    parse_status character varying(255) NOT NULL,
    statement_period_end character varying(255),
    statement_period_start character varying(255),
    storage_path character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT document_uploads_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['BANK_STATEMENT'::character varying, 'CREDIT_CARD_STATEMENT'::character varying, 'MF_STATEMENT'::character varying, 'DEMAT_STATEMENT'::character varying, 'UPI_STATEMENT'::character varying, 'TRANSACTION_RECEIPT'::character varying, 'UNKNOWN'::character varying])::text[]))),
    CONSTRAINT document_uploads_parse_status_check CHECK (((parse_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'PASSWORD_REQUIRED'::character varying])::text[])))
);
CREATE SEQUENCE public.document_uploads_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.document_uploads_id_seq OWNED BY public.document_uploads.id;
ALTER TABLE ONLY public.document_uploads ALTER COLUMN id SET DEFAULT nextval('public.document_uploads_id_seq'::regclass);
ALTER TABLE ONLY public.document_uploads ADD CONSTRAINT document_uploads_pkey PRIMARY KEY (id);

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    budget_category character varying(100),
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    expense_date date NOT NULL,
    is_recurring boolean,
    merchant character varying(255),
    notes text,
    payment_method character varying(255),
    recurring_frequency character varying(255),
    source character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT expenses_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD_DINING'::character varying, 'GROCERIES'::character varying, 'TRANSPORTATION'::character varying, 'UTILITIES'::character varying, 'ENTERTAINMENT'::character varying, 'SHOPPING'::character varying, 'HEALTHCARE'::character varying, 'INSURANCE'::character varying, 'SUBSCRIPTION'::character varying, 'INVESTMENT'::character varying, 'SAVINGS'::character varying, 'EDUCATION'::character varying, 'PERSONAL_CARE'::character varying, 'HOME_MAINTENANCE'::character varying, 'TRAVEL'::character varying, 'BUSINESS'::character varying, 'CHARITY'::character varying, 'DEBT_PAYMENT'::character varying, 'TAXES'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT expenses_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'CASH'::character varying, 'BANK_TRANSFER'::character varying, 'UPI'::character varying, 'WALLET'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT expenses_recurring_frequency_check CHECK (((recurring_frequency)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'MONTHLY'::character varying, 'QUARTERLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT expenses_source_check CHECK (((source)::text = ANY ((ARRAY['SMS'::character varying, 'MANUAL'::character varying, 'BANK_API'::character varying, 'APP_INTEGRATION'::character varying, 'BANK_PDF'::character varying, 'MF_PDF'::character varying, 'UPI_PDF'::character varying])::text[])))
);
ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.expenses ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

CREATE TABLE public.financial_goals (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    current_amount numeric(38,2) NOT NULL,
    description text,
    expected_annual_return numeric(38,2),
    inflation_rate numeric(38,2),
    last_alert_date timestamp(6) without time zone,
    linked_portfolio character varying(100),
    name character varying(255) NOT NULL,
    off_track_reason text,
    priority character varying(255),
    progress_percentage numeric(38,2) NOT NULL,
    required_monthly_amount numeric(38,2),
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    target_amount numeric(38,2) NOT NULL,
    target_date date NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT financial_goals_category_check CHECK (((category)::text = ANY ((ARRAY['SHORT_TERM'::character varying, 'MEDIUM_TERM'::character varying, 'LONG_TERM'::character varying])::text[]))),
    CONSTRAINT financial_goals_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT financial_goals_status_check CHECK (((status)::text = ANY ((ARRAY['ON_TRACK'::character varying, 'AT_RISK'::character varying, 'OFF_TRACK'::character varying, 'ACHIEVED'::character varying, 'ABANDONED'::character varying, 'PAUSED'::character varying])::text[]))),
    CONSTRAINT financial_goals_type_check CHECK (((type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'INVESTMENT'::character varying, 'DEBT_PAYOFF'::character varying, 'PURCHASE'::character varying, 'EMERGENCY_FUND'::character varying, 'EDUCATION'::character varying, 'RETIREMENT'::character varying, 'WEALTH_BUILDING'::character varying, 'PROPERTY'::character varying, 'VACATION'::character varying, 'OTHER'::character varying])::text[])))
);
ALTER TABLE public.financial_goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.financial_goals_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.financial_goals ADD CONSTRAINT financial_goals_pkey PRIMARY KEY (id);

CREATE TABLE public.investments (
    id bigint NOT NULL,
    cost_per_unit numeric(19,4) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_price numeric(19,4),
    current_value numeric(19,4),
    gain_loss_percentage numeric(10,4),
    is_active boolean NOT NULL,
    name character varying(255) NOT NULL,
    notes text,
    platform character varying(100),
    purchase_date date NOT NULL,
    quantity numeric(19,4) NOT NULL,
    realized_gain_loss numeric(19,4),
    risk_profile character varying(255),
    sale_date date,
    sector character varying(100),
    symbol character varying(50),
    total_cost numeric(19,4) NOT NULL,
    type character varying(255) NOT NULL,
    unrealized_gain_loss numeric(19,4),
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    investment_type character varying(255) NOT NULL,
    CONSTRAINT investments_investment_type_check CHECK (((investment_type)::text = ANY ((ARRAY['STOCK'::character varying, 'MUTUAL_FUND'::character varying, 'ETF'::character varying, 'BOND'::character varying, 'CRYPTOCURRENCY'::character varying, 'REAL_ESTATE'::character varying, 'GOLD'::character varying, 'COMMODITY'::character varying, 'FIXED_DEPOSIT'::character varying, 'POST_OFFICE_SCHEME'::character varying, 'PPF'::character varying, 'INSURANCE_POLICY'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT investments_risk_profile_check CHECK (((risk_profile)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT investments_type_check CHECK (((type)::text = ANY ((ARRAY['STOCK'::character varying, 'MUTUAL_FUND'::character varying, 'ETF'::character varying, 'BOND'::character varying, 'CRYPTOCURRENCY'::character varying, 'REAL_ESTATE'::character varying, 'GOLD'::character varying, 'COMMODITY'::character varying, 'FIXED_DEPOSIT'::character varying, 'POST_OFFICE_SCHEME'::character varying, 'PPF'::character varying, 'INSURANCE_POLICY'::character varying, 'OTHER'::character varying])::text[])))
);
ALTER TABLE public.investments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investments_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.investments ADD CONSTRAINT investments_pkey PRIMARY KEY (id);

CREATE TABLE public.portfolios (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL
);
ALTER TABLE public.portfolios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolios_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.portfolios ADD CONSTRAINT portfolios_pkey PRIMARY KEY (id);

-- Indexes
CREATE INDEX idx_budget_category ON public.budgets USING btree (category);
CREATE INDEX idx_budget_user_month ON public.budgets USING btree (user_id, budget_month);
CREATE INDEX idx_cfo_news_embedding_hnsw ON public.cfo_news_embeddings USING hnsw (embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_doc_status ON public.document_uploads USING btree (parse_status);
CREATE INDEX idx_doc_user ON public.document_uploads USING btree (user_id);
CREATE INDEX idx_expense_amount ON public.expenses USING btree (amount DESC);
CREATE INDEX idx_expense_category ON public.expenses USING btree (category);
CREATE INDEX idx_expense_date ON public.expenses USING btree (expense_date DESC);
CREATE INDEX idx_expense_month ON public.expenses USING btree (expense_date DESC, category);
CREATE INDEX idx_expense_user ON public.expenses USING btree (user_id);
CREATE INDEX idx_goal_priority ON public.financial_goals USING btree (priority);
CREATE INDEX idx_goal_status ON public.financial_goals USING btree (status);
CREATE INDEX idx_goal_target_date ON public.financial_goals USING btree (target_date);
CREATE INDEX idx_goal_user ON public.financial_goals USING btree (user_id);
CREATE INDEX idx_insight_date ON public.cfo_ai_insights USING btree (insight_date DESC);
CREATE INDEX idx_insight_type ON public.cfo_ai_insights USING btree (insight_type);
CREATE INDEX idx_investment_active ON public.investments USING btree (is_active);
CREATE INDEX idx_investment_date ON public.investments USING btree (purchase_date DESC);
CREATE INDEX idx_investment_purchase_date ON public.investments USING btree (purchase_date);
CREATE INDEX idx_investment_symbol ON public.investments USING btree (symbol);
CREATE INDEX idx_investment_type ON public.investments USING btree (investment_type);
CREATE INDEX idx_investment_user ON public.investments USING btree (user_id);
CREATE INDEX idx_investor_behavior_user ON public.cfo_investor_behavior USING btree (user_id);
CREATE INDEX idx_news_actionable ON public.cfo_news_articles USING btree (actionability_score DESC);
CREATE INDEX idx_news_date ON public.cfo_news_articles USING btree (published_date DESC);
CREATE INDEX idx_news_relevance ON public.cfo_news_articles USING btree (relevance_score DESC);
CREATE INDEX idx_news_source ON public.cfo_news_articles USING btree (source);
CREATE INDEX idx_pdf_status ON public.cfo_pdf_uploads USING btree (parse_status);
CREATE INDEX idx_pdf_user ON public.cfo_pdf_uploads USING btree (user_id);
CREATE INDEX idx_price_history_symbol_date ON public.cfo_stock_price_history USING btree (symbol, price_date DESC);
CREATE INDEX idx_snapshot_user_time ON public.cfo_portfolio_snapshots USING btree (user_id, snapshot_time DESC);
CREATE INDEX idx_txn_source ON public.cfo_transactions USING btree (source);
CREATE INDEX idx_txn_type ON public.cfo_transactions USING btree (transaction_type);
CREATE INDEX idx_txn_user_date ON public.cfo_transactions USING btree (user_id, transaction_date DESC);
