-- Phase 1: Auth tables
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_uq UNIQUE (username),
    CONSTRAINT users_email_uq UNIQUE (email)
);

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- DF-6: Article entity graph
CREATE TABLE public.cfo_article_entity (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    article_id bigint NOT NULL,
    entity_type character varying(16) NOT NULL,
    entity_id character varying(100) NOT NULL,
    confidence double precision NOT NULL DEFAULT 0.0,
    source character varying(12) NOT NULL,
    created_at timestamp(6) without time zone,
    CONSTRAINT cfo_article_entity_pkey PRIMARY KEY (id),
    CONSTRAINT uq_article_entity UNIQUE (article_id, entity_type, entity_id, source)
);
CREATE INDEX idx_article_entity_article ON public.cfo_article_entity USING btree (article_id);
CREATE INDEX idx_article_entity_entity ON public.cfo_article_entity USING btree (entity_type, entity_id);

-- DF-6: News cluster (dedup groups)
CREATE TABLE public.cfo_news_cluster (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    canonical_article_id bigint NOT NULL,
    title text,
    first_seen timestamp(6) without time zone NOT NULL,
    last_seen timestamp(6) without time zone,
    article_count integer DEFAULT 1,
    CONSTRAINT cfo_news_cluster_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_news_cluster_first_seen ON public.cfo_news_cluster USING btree (first_seen DESC);
CREATE INDEX idx_news_cluster_canonical ON public.cfo_news_cluster USING btree (canonical_article_id);

-- DF-6: Market event (structured from cluster)
CREATE TABLE public.cfo_market_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cluster_id bigint NOT NULL,
    event_type character varying(20) NOT NULL,
    event_date date NOT NULL,
    structured_payload jsonb,
    created_at timestamp(6) without time zone,
    CONSTRAINT cfo_market_event_pkey PRIMARY KEY (id),
    CONSTRAINT uq_market_event_cluster UNIQUE (cluster_id)
);
CREATE INDEX idx_market_event_date ON public.cfo_market_event USING btree (event_date DESC);
CREATE INDEX idx_market_event_cluster ON public.cfo_market_event USING btree (cluster_id);

-- DF-6: Event outcome (realized returns vs news)
CREATE TABLE public.cfo_event_outcome (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    cluster_id bigint NOT NULL,
    instrument_id bigint NOT NULL,
    symbol character varying(30),
    horizon character varying(6) NOT NULL,
    event_date date,
    raw_return double precision,
    excess_return_vs_nifty double precision,
    computed_at timestamp(6) without time zone,
    CONSTRAINT cfo_event_outcome_pkey PRIMARY KEY (id),
    CONSTRAINT uq_event_outcome UNIQUE (cluster_id, instrument_id, horizon)
);
CREATE INDEX idx_event_outcome_cluster ON public.cfo_event_outcome USING btree (cluster_id);
CREATE INDEX idx_event_outcome_instrument ON public.cfo_event_outcome USING btree (instrument_id);

-- DF-7: Insight claim (calibration scoreboard)
CREATE TABLE public.cfo_insight_claim (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    insight_id bigint NOT NULL,
    user_id character varying(255) NOT NULL,
    insight_date date NOT NULL,
    symbol character varying(30) NOT NULL,
    direction character varying(8) NOT NULL,
    horizon character varying(6) NOT NULL,
    confidence double precision NOT NULL,
    expected_return double precision,
    thesis character varying(500),
    provider character varying(20),
    prompt_version character varying(20),
    scored boolean NOT NULL DEFAULT false,
    raw_return double precision,
    excess_return_vs_nifty double precision,
    correct boolean,
    scored_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT cfo_insight_claim_pkey PRIMARY KEY (id),
    CONSTRAINT uq_claim_insight_symbol_horizon UNIQUE (insight_id, symbol, horizon)
);
CREATE INDEX idx_claim_insight ON public.cfo_insight_claim USING btree (insight_id);
CREATE INDEX idx_claim_scored ON public.cfo_insight_claim USING btree (scored);
CREATE INDEX idx_claim_provider_version ON public.cfo_insight_claim USING btree (provider, prompt_version);

-- DF-3: Macro time series
CREATE TABLE public.cfo_macro_series (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    series_code character varying(24) NOT NULL,
    obs_date date NOT NULL,
    value numeric(18,6) NOT NULL,
    source character varying(20),
    created_at timestamp(6) without time zone,
    CONSTRAINT cfo_macro_series_pkey PRIMARY KEY (id),
    CONSTRAINT uq_macro_series_code_date UNIQUE (series_code, obs_date)
);
CREATE INDEX idx_macro_series_code_date ON public.cfo_macro_series USING btree (series_code, obs_date DESC);

-- Macro snapshot
CREATE TABLE public.cfo_macro_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    snapshot_date date NOT NULL,
    repo_rate numeric(8,2),
    repo_rate_as_of date,
    cpi_yo_y numeric(8,2),
    cpi_as_of character varying(20),
    usd_inr numeric(8,2),
    usd_inr_fetched_at timestamp(6) without time zone,
    india_vix numeric(8,2),
    india_vix_fetched_at timestamp(6) without time zone,
    gsec3m numeric(8,2),
    gsec1y numeric(8,2),
    gsec5y numeric(8,2),
    gsec_yield10_y numeric(8,2),
    gsec_yield_as_of date,
    curve_slope10y3m numeric(8,2),
    gdp_growth numeric(8,2),
    gdp_as_of date,
    fii_net_flow numeric(12,2),
    dii_net_flow numeric(12,2),
    fii_net_flow5d numeric(12,2),
    flows_as_of date,
    data_quality_notes character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT cfo_macro_snapshot_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_macro_snapshot_date ON public.cfo_macro_snapshot USING btree (snapshot_date DESC);

-- Phase 8: Quarterly fundamentals
CREATE TABLE public.cfo_quarterly_fundamentals (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    symbol character varying(30) NOT NULL,
    quarter_end date NOT NULL,
    revenue numeric(18,2),
    net_income numeric(18,2),
    eps numeric(10,2),
    total_assets numeric(18,2),
    total_liabilities numeric(18,2),
    shares_outstanding numeric(12,0),
    operating_cash_flow numeric(18,2),
    gross_margin numeric(8,2),
    trend_confidence character varying(20) NOT NULL DEFAULT 'LOW',
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT cfo_quarterly_fundamentals_pkey PRIMARY KEY (id),
    CONSTRAINT uq_quarterly_symbol_quarter UNIQUE (symbol, quarter_end)
);
CREATE INDEX idx_quarterly_symbol_date ON public.cfo_quarterly_fundamentals USING btree (symbol, quarter_end DESC);

-- Phase 8: Stock fundamentals (daily snapshot)
CREATE TABLE public.cfo_stock_fundamentals (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    symbol character varying(30) NOT NULL,
    snapshot_date date NOT NULL,
    trailing_pe numeric(10,2),
    forward_pe numeric(10,2),
    price_to_book numeric(10,2),
    ev_to_ebitda numeric(10,2),
    ev_to_sales numeric(10,2),
    peg_ratio numeric(10,2),
    dividend_yield numeric(8,2),
    revenue_growth numeric(8,2),
    gross_margin numeric(8,2),
    ebitda_margin numeric(8,2),
    operating_margin numeric(8,2),
    net_profit_margin numeric(8,2),
    roe numeric(8,2),
    debt_to_equity numeric(10,2),
    free_cash_flow numeric(16,0),
    is_profitable boolean,
    pe_z_score numeric(8,2),
    ev_ebitda_z_score numeric(8,2),
    valuation_label character varying(20),
    peer_group character varying(80),
    peer_pe_percentile numeric(8,2),
    peer_pb_percentile numeric(8,2),
    net_interest_margin numeric(8,2),
    gross_npa numeric(8,2),
    net_npa numeric(8,2),
    casa_ratio numeric(8,2),
    credit_cost numeric(8,2),
    provision_coverage_ratio numeric(8,2),
    piotroski_f_score integer,
    piotroski_max_checks integer,
    piotroski_detail character varying(300),
    data_quality_notes character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT cfo_stock_fundamentals_pkey PRIMARY KEY (id),
    CONSTRAINT uq_fundamentals_symbol_date UNIQUE (symbol, snapshot_date)
);
CREATE INDEX idx_fundamentals_symbol_date ON public.cfo_stock_fundamentals USING btree (symbol, snapshot_date DESC);

-- Phase 5c: Stock scorecard snapshot
CREATE TABLE public.cfo_stock_scorecard_snapshot (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    symbol character varying(30) NOT NULL,
    scorecard_date date NOT NULL,
    total_score double precision NOT NULL,
    recommendation character varying(30) NOT NULL,
    confidence integer NOT NULL,
    expected_return_band character varying(30),
    scorecard_json text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT cfo_stock_scorecard_snapshot_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_scorecard_snapshot_symbol_date ON public.cfo_stock_scorecard_snapshot USING btree (symbol, scorecard_date DESC);

-- Phase 12: MF portfolio holdings (look-through)
CREATE TABLE public.cfo_mf_portfolio_holdings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    scheme_code character varying(40) NOT NULL,
    as_of date NOT NULL,
    isin character varying(20),
    symbol character varying(50),
    weight_pct double precision NOT NULL,
    sector character varying(100),
    created_at timestamp(6) without time zone,
    CONSTRAINT cfo_mf_portfolio_holdings_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_mfph_scheme_asof ON public.cfo_mf_portfolio_holdings USING btree (scheme_code, as_of);
CREATE INDEX idx_mfph_isin ON public.cfo_mf_portfolio_holdings USING btree (isin);
CREATE INDEX idx_mfph_symbol ON public.cfo_mf_portfolio_holdings USING btree (symbol);

-- DF-1: Instrument master
CREATE TABLE public.md_instrument (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    isin character varying(12) NOT NULL,
    symbol character varying(30) NOT NULL,
    series character varying(4),
    name character varying(120),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT md_instrument_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_instrument_isin UNIQUE (isin)
);
CREATE INDEX idx_md_instrument_symbol ON public.md_instrument USING btree (symbol);

-- DF-1: EOD prices (NSE bhavcopy)
CREATE TABLE public.md_eod_price (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint NOT NULL,
    trade_date date NOT NULL,
    symbol character varying(30) NOT NULL,
    open numeric(14,2),
    high numeric(14,2),
    low numeric(14,2),
    close numeric(14,2),
    last numeric(14,2),
    prev_close numeric(14,2),
    adj_close numeric(18,6),
    volume bigint,
    turnover numeric(18,2),
    trades bigint,
    series character varying(4),
    vwap numeric(14,2),
    deliv_qty bigint,
    deliv_pct numeric(6,2),
    source character varying(20),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_eod_price_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_eod_instrument_date UNIQUE (instrument_id, trade_date)
);
CREATE INDEX idx_md_eod_trade_date ON public.md_eod_price USING btree (trade_date);
CREATE INDEX idx_md_eod_symbol_date ON public.md_eod_price USING btree (symbol, trade_date);

-- DF-1: Index EOD (NSE index closes)
CREATE TABLE public.md_index_eod (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    index_name character varying(80) NOT NULL,
    trade_date date NOT NULL,
    open numeric(14,2),
    high numeric(14,2),
    low numeric(14,2),
    close numeric(14,2),
    points_change numeric(14,2),
    change_pct numeric(8,2),
    volume bigint,
    turnover_cr numeric(18,2),
    pe numeric(10,2),
    pb numeric(10,2),
    div_yield numeric(8,2),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_index_eod_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_index_eod_name_date UNIQUE (index_name, trade_date)
);
CREATE INDEX idx_md_index_eod_name_date ON public.md_index_eod USING btree (index_name, trade_date DESC);

-- DF-5: Ingestion run ledger
CREATE TABLE public.md_ingestion_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    job_name character varying(40) NOT NULL,
    business_date date NOT NULL,
    status character varying(12) NOT NULL,
    row_count integer,
    message character varying(500),
    started_at timestamp(6) without time zone,
    finished_at timestamp(6) without time zone,
    CONSTRAINT md_ingestion_run_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_ingestion_job_date UNIQUE (job_name, business_date)
);
CREATE INDEX idx_md_ingestion_job_date ON public.md_ingestion_run USING btree (job_name, business_date DESC);

-- DF-4: MF scheme master
CREATE TABLE public.md_mf_scheme (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    amfi_code character varying(12) NOT NULL,
    isin character varying(20),
    isin_reinvest character varying(20),
    scheme_name character varying(300) NOT NULL,
    amc character varying(200),
    category character varying(200),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT md_mf_scheme_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_mf_scheme_amfi_code UNIQUE (amfi_code)
);
CREATE INDEX idx_md_mf_scheme_isin ON public.md_mf_scheme USING btree (isin);
CREATE INDEX idx_md_mf_scheme_category ON public.md_mf_scheme USING btree (category);

-- DF-4: MF NAV
CREATE TABLE public.md_mf_nav (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    amfi_code character varying(12) NOT NULL,
    nav_date date NOT NULL,
    nav numeric(18,6) NOT NULL,
    created_at timestamp(6) without time zone,
    CONSTRAINT md_mf_nav_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_mf_nav_code_date UNIQUE (amfi_code, nav_date)
);
CREATE INDEX idx_md_mf_nav_code_date ON public.md_mf_nav USING btree (amfi_code, nav_date DESC);

-- DF-4: Corporate actions
CREATE TABLE public.md_corporate_action (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint,
    isin character varying(12) NOT NULL,
    symbol character varying(30) NOT NULL,
    series character varying(4),
    company_name character varying(160),
    action_type character varying(12) NOT NULL,
    subject character varying(400) NOT NULL,
    ex_date date,
    record_date date,
    ratio_new integer,
    ratio_old integer,
    from_face_value numeric(10,2),
    to_face_value numeric(10,2),
    dividend_amount numeric(12,4),
    dedup_hash character varying(64) NOT NULL,
    source character varying(20),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_corporate_action_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_ca_dedup UNIQUE (dedup_hash)
);
CREATE INDEX idx_md_ca_symbol_exdate ON public.md_corporate_action USING btree (symbol, ex_date);
CREATE INDEX idx_md_ca_instrument ON public.md_corporate_action USING btree (instrument_id);
CREATE INDEX idx_md_ca_exdate ON public.md_corporate_action USING btree (ex_date);

-- DF-2: Corporate events calendar
CREATE TABLE public.md_corporate_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint,
    symbol character varying(30) NOT NULL,
    company_name character varying(160),
    event_type character varying(16) NOT NULL,
    event_date date NOT NULL,
    description character varying(500),
    payload jsonb,
    dedup_hash character varying(64) NOT NULL,
    source character varying(24),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_corporate_event_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_event_dedup UNIQUE (dedup_hash)
);
CREATE INDEX idx_md_event_symbol_date ON public.md_corporate_event USING btree (symbol, event_date);
CREATE INDEX idx_md_event_date ON public.md_corporate_event USING btree (event_date);
CREATE INDEX idx_md_event_type ON public.md_corporate_event USING btree (event_type);

-- DF-4: Bulk/block deals
CREATE TABLE public.md_market_deal (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint,
    deal_type character varying(6) NOT NULL,
    deal_date date NOT NULL,
    symbol character varying(30) NOT NULL,
    security_name character varying(200),
    client_name character varying(300),
    side character varying(4),
    quantity bigint,
    price numeric(14,2),
    dedup_hash character varying(64) NOT NULL,
    source character varying(20),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_market_deal_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_deal_dedup UNIQUE (dedup_hash)
);
CREATE INDEX idx_md_deal_symbol_date ON public.md_market_deal USING btree (symbol, deal_date DESC);
CREATE INDEX idx_md_deal_instrument ON public.md_market_deal USING btree (instrument_id);
CREATE INDEX idx_md_deal_date_type ON public.md_market_deal USING btree (deal_date DESC, deal_type);

-- Price adjustment factors (back-adjustment)
CREATE TABLE public.md_price_adjustment (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint NOT NULL,
    ex_date date NOT NULL,
    action_type character varying(12) NOT NULL,
    factor numeric(18,10) NOT NULL,
    description character varying(200),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_price_adjustment_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_padj_event UNIQUE (instrument_id, ex_date, action_type)
);
CREATE INDEX idx_md_padj_instrument ON public.md_price_adjustment USING btree (instrument_id);

-- DF-4: NSE corporate announcements
CREATE TABLE public.md_announcement (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint,
    symbol character varying(30),
    company_name character varying(200),
    subject character varying(200),
    details character varying(2000),
    broadcast_at timestamp(6) without time zone,
    attachment_url character varying(500),
    dedup_hash character varying(64) NOT NULL,
    source character varying(20),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_announcement_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_ann_dedup UNIQUE (dedup_hash)
);
CREATE INDEX idx_md_ann_symbol_time ON public.md_announcement USING btree (symbol, broadcast_at DESC);
CREATE INDEX idx_md_ann_instrument ON public.md_announcement USING btree (instrument_id);
CREATE INDEX idx_md_ann_time ON public.md_announcement USING btree (broadcast_at DESC);

-- DF-4: Shareholding patterns
CREATE TABLE public.md_shareholding_pattern (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    instrument_id bigint,
    symbol character varying(30) NOT NULL,
    company_name character varying(200),
    period_ended date NOT NULL,
    promoter_pct numeric(8,4),
    promoter_pledge_pct numeric(8,4),
    fii_pct numeric(8,4),
    dii_pct numeric(8,4),
    public_pct numeric(8,4),
    source character varying(20),
    created_at timestamp(6) without time zone,
    CONSTRAINT md_shareholding_pattern_pkey PRIMARY KEY (id),
    CONSTRAINT uq_md_shp_symbol_period UNIQUE (symbol, period_ended)
);
CREATE INDEX idx_md_shp_symbol_period ON public.md_shareholding_pattern USING btree (symbol, period_ended DESC);
CREATE INDEX idx_md_shp_instrument ON public.md_shareholding_pattern USING btree (instrument_id);

-- Policy intelligence
CREATE TABLE public.policy_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    document_key character varying(200) NOT NULL,
    authority character varying(50) NOT NULL,
    document_type character varying(50) NOT NULL,
    binding_level character varying(50) NOT NULL,
    policy_area character varying(50) NOT NULL,
    status character varying(50) NOT NULL DEFAULT 'ACTIVE',
    title text NOT NULL,
    source_url text,
    source_reference character varying(300),
    external_document_id character varying(200),
    latest_version_number integer DEFAULT 1,
    published_date date,
    effective_from date,
    effective_to date,
    tags_csv character varying(1000),
    affected_sectors_csv character varying(1000),
    summary text,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT policy_documents_pkey PRIMARY KEY (id),
    CONSTRAINT policy_documents_key_uq UNIQUE (document_key)
);
CREATE INDEX idx_policy_doc_authority ON public.policy_documents USING btree (authority);
CREATE INDEX idx_policy_doc_area ON public.policy_documents USING btree (policy_area);
CREATE INDEX idx_policy_doc_status ON public.policy_documents USING btree (status);
CREATE INDEX idx_policy_doc_source_ref ON public.policy_documents USING btree (source_reference);
CREATE INDEX idx_policy_doc_external_id ON public.policy_documents USING btree (external_document_id);
CREATE UNIQUE INDEX idx_policy_doc_key ON public.policy_documents USING btree (document_key);

CREATE TABLE public.policy_document_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    document_id bigint NOT NULL,
    version_number integer NOT NULL,
    version_label character varying(100),
    supersedes_reference character varying(200),
    content_hash character varying(64) NOT NULL,
    is_current boolean NOT NULL DEFAULT true,
    issued_at timestamp(6) without time zone,
    effective_from date,
    effective_to date,
    summary text,
    normalized_text text NOT NULL,
    metadata_json text,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT policy_document_versions_pkey PRIMARY KEY (id),
    CONSTRAINT policy_versions_doc_fk FOREIGN KEY (document_id) REFERENCES public.policy_documents(id)
);
CREATE INDEX idx_policy_version_doc ON public.policy_document_versions USING btree (document_id);
CREATE INDEX idx_policy_version_current ON public.policy_document_versions USING btree (is_current);
CREATE INDEX idx_policy_version_hash ON public.policy_document_versions USING btree (content_hash);

CREATE TABLE public.policy_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    heading character varying(300),
    section_path character varying(500),
    citation_label character varying(300),
    page_number_start integer,
    page_number_end integer,
    content text NOT NULL,
    keyword_text text,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT policy_chunks_pkey PRIMARY KEY (id),
    CONSTRAINT policy_chunks_version_fk FOREIGN KEY (version_id) REFERENCES public.policy_document_versions(id)
);
CREATE INDEX idx_policy_chunk_version ON public.policy_chunks USING btree (version_id);
CREATE INDEX idx_policy_chunk_order ON public.policy_chunks USING btree (version_id, chunk_index);

CREATE TABLE public.policy_impacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    document_id bigint NOT NULL,
    version_id bigint,
    policy_area character varying(50) NOT NULL,
    subject_type character varying(50) NOT NULL,
    subject_key character varying(100) NOT NULL,
    subject_label character varying(200) NOT NULL,
    action_type character varying(50),
    transmission_channel character varying(50),
    affected_party character varying(300),
    direction character varying(30) NOT NULL,
    horizon character varying(30) NOT NULL,
    effective_from date,
    effective_to date,
    implementation_summary text,
    surprise_classification character varying(50),
    legal_force_rank integer,
    market_moving_power integer,
    confidence_score double precision,
    impact_summary text NOT NULL,
    reasoning_note text,
    falsification_signal text,
    tags_csv character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT policy_impacts_pkey PRIMARY KEY (id),
    CONSTRAINT policy_impacts_doc_fk FOREIGN KEY (document_id) REFERENCES public.policy_documents(id),
    CONSTRAINT policy_impacts_version_fk FOREIGN KEY (version_id) REFERENCES public.policy_document_versions(id)
);
CREATE INDEX idx_policy_impact_doc ON public.policy_impacts USING btree (document_id);
CREATE INDEX idx_policy_impact_subject ON public.policy_impacts USING btree (subject_type, subject_key);
CREATE INDEX idx_policy_impact_area ON public.policy_impacts USING btree (policy_area);
CREATE INDEX idx_policy_impact_effective ON public.policy_impacts USING btree (effective_from);
